POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
  "email": "danny.lopez@devstack.com",
  "password": "Tester017!"
}

###

POST {{baseUrl}}/authentication/register
Content-Type: application/json

{
  "email": "danny.lopez@devstack.com",
  "password": "Tester017!"
}